version: "3.8"

services:
  moleculer:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: "178.16.142.77"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "incidentdb"
      POSTGRES_USER: "adminsp"
      POSTGRES_PASSWORD: "4SxYdhnha3g6uhgndTvD"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "incidentdb"
      POSTGRES_USER: "adminsp"
      POSTGRES_PASSWORD: "4SxYdhnha3g6uhgndTvD"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
